<a href="https://colab.research.google.com/github/JulesDimanche/Machine-Learning/blob/main/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
sent=['the glass of milk','the glass of juice','the cup of tea','I am good boy','I am good developer','I am not a good developer']

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am good boy',
 'I am good developer',
 'I am not a good developer']

In [ ]:
voc_size=1000

In [ ]:
onehot=[one_hot(word,voc_size)for word in sent]
onehot

[[200, 946, 692, 337],
 [200, 946, 692, 449],
 [200, 456, 692, 989],
 [198, 872, 753, 471],
 [198, 872, 753, 821],
 [198, 872, 343, 5, 753, 821]]

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

Padding

In [ ]:
#pre padding
#padding is to make the input size as same.
sent_length=8 #take length that is more than max sent length
embed_doc=pad_sequences(onehot,padding='pre',maxlen=sent_length)
embed_doc

array([[  0,   0,   0,   0, 200, 946, 692, 337],
       [  0,   0,   0,   0, 200, 946, 692, 449],
       [  0,   0,   0,   0, 200, 456, 692, 989],
       [  0,   0,   0,   0, 198, 872, 753, 471],
       [  0,   0,   0,   0, 198, 872, 753, 821],
       [  0,   0, 198, 872, 343,   5, 753, 821]], dtype=int32)

In [ ]:
#feature dimensions
dim=10

In [ ]:
from tensorflow.keras.layers import Input

model=Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
embed_doc[0]

array([  0,   0,   0,   0, 200, 946, 692, 337], dtype=int32)

In [ ]:
model.predict(embed_doc[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 920ms/step


array([[ 0.03237459, -0.00799077,  0.03755153, -0.00792255, -0.03091098,
         0.00811373, -0.02757977, -0.00482154, -0.00812305, -0.04999191],
       [ 0.03237459, -0.00799077,  0.03755153, -0.00792255, -0.03091098,
         0.00811373, -0.02757977, -0.00482154, -0.00812305, -0.04999191],
       [ 0.03237459, -0.00799077,  0.03755153, -0.00792255, -0.03091098,
         0.00811373, -0.02757977, -0.00482154, -0.00812305, -0.04999191],
       [ 0.03237459, -0.00799077,  0.03755153, -0.00792255, -0.03091098,
         0.00811373, -0.02757977, -0.00482154, -0.00812305, -0.04999191],
       [ 0.00677371,  0.00236423, -0.03488078,  0.00692606, -0.00688281,
         0.04672189, -0.01197471, -0.03049357, -0.03710916, -0.00830274],
       [ 0.02012856,  0.00106065,  0.00348096,  0.03444121,  0.01688092,
         0.031378  , -0.00030545,  0.0308046 , -0.03306115, -0.00063796],
       [-0.04843182, -0.00568762,  0.03152498, -0.01412028,  0.04741755,
         0.04413098, -0.02607059,  0.03962355

In [ ]:
model.predict(np.array(embed_doc).reshape(len(embed_doc), sent_length))

1/1 ━━━━━━━━━━━━━━━━━━━━ 18s 18s/step


array([[[ 3.36581357e-02,  3.35329808e-02,  1.67021863e-02,
          1.03000030e-02, -4.82583046e-02,  8.61656666e-03,
          3.58529128e-02, -3.74745131e-02,  4.66685370e-03,
          2.30204947e-02],
        [ 3.36581357e-02,  3.35329808e-02,  1.67021863e-02,
          1.03000030e-02, -4.82583046e-02,  8.61656666e-03,
          3.58529128e-02, -3.74745131e-02,  4.66685370e-03,
          2.30204947e-02],
        [ 3.36581357e-02,  3.35329808e-02,  1.67021863e-02,
          1.03000030e-02, -4.82583046e-02,  8.61656666e-03,
          3.58529128e-02, -3.74745131e-02,  4.66685370e-03,
          2.30204947e-02],
        [ 3.36581357e-02,  3.35329808e-02,  1.67021863e-02,
          1.03000030e-02, -4.82583046e-02,  8.61656666e-03,
          3.58529128e-02, -3.74745131e-02,  4.66685370e-03,
          2.30204947e-02],
        [ 8.26064497e-03, -1.74789205e-02, -2.36160997e-02,
          4.52595092e-02,  1.46027915e-02, -2.02371478e-02,
         -2.77787577e-02, -4.20920551e-05, -2.455982

In [ ]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │        10,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,000 (39.06 KB)

 Trainable params: 10,000 (39.06 KB)

 Non-trainable params: 0 (0.00 B)